networks:
  dspacenet:
    ipam:
      config:
        - subnet: 172.21.0.0/16

services:
  dspace:
    container_name: dspace
    image: dspace/dspace:dspace-9_x

    environment:
      dspace__P__dir: /dspace
      dspace__P__name: "${DSPACE_NAME}"
      db__P__url: "${DSPACE_DB_URL}"
      db__P__username: "${DSPACE_DB_USER}"
      db__P__password: "${DSPACE_DB_PASSWORD}"
      solr__P__server: "${DSPACE_SOLR_URL}"
      proxies__P__trusted__P__ipranges: "172.21.0"
      LOGGING_CONFIG: /dspace/config/log4j2-container.xml

    depends_on:
      - dspacedb
      - dspacesolr

    networks:
      - dspacenet

    ports:
      - "8080:8080"

    stdin_open: true
    tty: true

    volumes:
      - ${DSPACE_ASSETSTORE_DIR}:/dspace/assetstore
      - ${DSPACE_CONFIG_DIR}:/dspace/config

    entrypoint:
      - /bin/bash
      - -c
      - |
        while ! </dev/tcp/dspacedb/5432; do
          echo "Aguardando PostgreSQL..."
          sleep 2
        done

        while ! </dev/tcp/dspacesolr/8983; do
          echo "Aguardando Solr..."
          sleep 2
        done

        /dspace/bin/dspace database migrate

        exec java -jar /dspace/webapps/server-boot.jar --dspace.dir=/dspace

  dspace-cli:
    container_name: dspace-cli
    image: dspace/dspace-cli:dspace-9_x

    depends_on:
      - dspacedb

    networks:
      - dspacenet

    stdin_open: true
    tty: true

    environment:
      db__P__url: "${DSPACE_DB_URL}"
      db__P__username: "${DSPACE_DB_USER}"
      db__P__password: "${DSPACE_DB_PASSWORD}"

    entrypoint:
      - /bin/bash

    volumes:
      - ${DSPACE_ASSETSTORE_DIR}:/dspace/assetstore
      - ${DSPACE_CONFIG_DIR}:/dspace/config

  dspacedb:
    container_name: dspacedb
    image: postgres:16

    environment:
      POSTGRES_DB: "${DSPACE_DB_NAME}"
      POSTGRES_USER: "${DSPACE_DB_USER}"
      POSTGRES_PASSWORD: "${DSPACE_DB_PASSWORD}"
      PGDATA: /pgdata

    networks:
      - dspacenet

    stdin_open: true
    tty: true

    volumes:
      - ${POSTGRES_DATA_DIR}:/pgdata

  dspacesolr:
    container_name: dspacesolr
    image: dspace/dspace-solr:dspace-9.0

    user: root

    networks:
      - dspacenet

    ports:
      - "127.0.0.1:8983:8983"

    stdin_open: true
    tty: true

    working_dir: /var/solr/data

    volumes:
      - ${SOLR_DATA_DIR}:/var/solr/data

    entrypoint:
      - /bin/bash
      - -c
      - |
        init-var-solr

        precreate-core authority /opt/solr/server/solr/configsets/authority
        cp -rn /opt/solr/server/solr/configsets/authority/* authority

        precreate-core oai /opt/solr/server/solr/configsets/oai
        cp -rn /opt/solr/server/solr/configsets/oai/* oai

        precreate-core search /opt/solr/server/solr/configsets/search
        cp -rn /opt/solr/server/solr/configsets/search/* search

        precreate-core statistics /opt/solr/server/solr/configsets/statistics
        cp -rn /opt/solr/server/solr/configsets/statistics/* statistics

        precreate-core qaevent /opt/solr/server/solr/configsets/qaevent
        cp -rn /opt/solr/server/solr/configsets/qaevent/* qaevent

        precreate-core suggestion /opt/solr/server/solr/configsets/suggestion
        cp -rn /opt/solr/server/solr/configsets/suggestion/* suggestion

        chown -R solr:solr /var/solr

        exec runuser -u solr -- solr-foreground
